gitlab-ci bug workaround
I have jobs that succeed even though the script is failing :

Linking ../bin/grafx2-sdl2
/usr/bin/ld: ../obj/unix-sdl2/miscfileformats.o: undefined reference to symbol 'uncompress'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:1040: recipe for target '../bin/grafx2-sdl2' failed
make[1]: *** [../bin/grafx2-sdl2] Error 1
make[1]: Leaving directory '/builds/miniupnp/grafX2/src'
Makefile:17: recipe for target 'grafx2' failed
make: *** [grafx2] Error 2
[...]
Job succeeded

https://gitlab.com/gitlab-com/support-forum/issues/1311