fix link with zlib.
GPX decoding uses zlib. It should be explicitely linked or else it produces
errors :

Linking ../bin/grafx2-sdl
/usr/bin/ld: ../obj/unix-sdl/miscfileformats.o: undefined reference to symbol 'uncompress'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line